### ISSUE TITLE
spawning robot with specific initial orientation

### ISSUE THREAD

**Issue by ndehio** [corlab/rtt-gazebo-embedded#20]
The method "spawn_model_at_pos" enables to specify the initial position of the robot.
Please add another method to specify the initial orientation as well.

**Comment by xwavex** [comment]
We should use the rstrt::geometry::Pose here

**Comment by ndehio** [comment]
I implemented the feature and uploaded to the branch: "feature_spawn_model_with_initial_orientation".
Please check and merge into master.

**Comment by xwavex** [comment]
I'll check that out

**Comment by ndehio** [comment]
The feature was successfully merged into master by Dennis, thanks!
I deleted the feature-branch.
This issue can be closed.
