### ISSUE TITLE
Error because of RTT::OwnThread

### ISSUE THREAD

**Issue by ndehio** [corlab/rtt-gazebo-embedded#21]
Using RTT::OperationCaller, I am able to call the operation gazebo.reset_world() from cpp code.
Unfortunately, calling the operation gazebo.reset_model_poses() from cpp code results in error:

> 5.089 [ ERROR  ][Logger] You're using call() an OwnThread operation or collect() on a sent operation without setting a caller in the OperationCaller. This often causes deadlocks.
> 5.089 [ ERROR  ][Logger] Use this->engine() in a component or GlobalEngine::Instance() in a non-component function. Returning a CollectFailure.
> 5.089 [ ERROR  ][Logger] in updateHook(): switching to exception state because of unhandled exception
> 

This is because "reset_world" is executed in the client-thread, while "reset_model_poses" is executed in its own-thread. Why is this the case?
See lines 59-63 in file:
https://github.com/corlab/rtt-gazebo-embedded/blob/master/src/rtt_gazebo_embedded.cc

I propose to change line 60 from from RTT::OwnThread to RTT::ClientThread. Do you agree?

**Comment by xwavex** [comment]
changed in https://github.com/corlab/rtt-gazebo-embedded/commit/816f5f75a7cc9981298ebe230379ad1b5f61eaa7
