### ISSUE TITLE
Do we need rtt-transport-corba here?

### ISSUE THREAD

**Issue by Pouya-moh** [corlab/rtt-gazebo-embedded#3]
I'm referring to [CMakeList.txt](https://github.com/corlab/rtt-gazebo-embedded/blob/master/CMakeLists.txt#L11). Particularly, I remember (I could be wrong) that @swrede wanted a corba-free solution and in orocos-rtt homebrew formula he specifically turned that off. Just wanted to check, since if corba _is_ needed, then homebrew formulas for osx need to be changed.

**Comment by xwavex** [comment]
No just remove it from the cmake and go ahead :) should work

**Comment by swrede** [comment]
@xwavex What do you mean by removing? I still prefer a corba-free solution if possible, which is the reason that I switched it **off**.

**Comment by xwavex** [comment]
I guess we don't need to use the corba-package at all, so removing it from the cmake should do the trick: 2a13e48. But I guess we have some **boost** issues on osx. At least I was facing some.

**Comment by Pouya-moh** [comment]
> No just remove it from the cmake and go ahead

Actually this is what I was doing. My issue was to be sure we are not corba-free on osx and cobra-dependant on linux. I will get back to your issue about boost tomorrow. I guess I know what is your problem.

**Comment by swrede** [comment]
@Pouya-moh Thanks for the clarification. Of course, it it is good to remove the corba dependency from the CMakeLists.txt if we can live without it.

**Comment by xwavex** [comment]
We are corba free now :-)
