### ISSUE TITLE
Sensor issue

### ISSUE THREAD

**Issue by smithjoshua001** [corlab/rtt-gazebo-embedded#8]
I'm having a problem whilst trying to run the force_torque sensor with the embedded gazebo. When running it with gazebo standing alone it runs without issue and the topic within gazebo at least gets updated force_torque readings, however, when I start the gazebo via this embedded way with OROCOS the sensor is registered and started, however, it never updates itself and when I try to check on the gazebo topics on the client it shows that no data is being used.
Is there something about starting gazebo this way that stops the sensor from running properly?
Here is the SDF file I've been using trying to simulated a 6 axis ft sensor at the end effector of a kuka-lwr arm: (uploaded as txt as github won't allow me to have the sdf extension)
[model.txt](https://github.com/corlab/rtt-gazebo-embedded/files/402091/model.txt)

**Comment by xwavex** [comment]
I will look into it. I think the issue it that in the embedded version extensive plugin handling is not provided out of the box.

**Comment by smithjoshua001** [comment]
I've actually solved it in a way on a local clone of the repository, there are a few functions that need calling to work like gazebo::sensors::run_threads and gazebo::sensors::run_once() I think, I'll fork and push an update for the version I've made work

**Comment by xwavex** [comment]
@smithjoshua001 This can be closed right?
